/* Insdu contract for Jurusan, measurements, capture coordinates, capacity, and reference distance. */
function insduContractError_(code, message) { var error=new Error(message); error.insduCode=code; throw error; }
function insduJurusanInteger_(value,label){var text=String(value==null?'':value).trim();if(!/^[1-4]$/.test(text))insduContractError_('INSDU_JURUSAN_RANGE_INVALID',label+' wajib berupa bilangan bulat 1 sampai 4.');return Number(text);}
function validateInsduJurusan_(incoming){var installed=insduJurusanInteger_(incoming['Jurusan Terpasang'],'Jurusan Terpasang'),used=insduJurusanInteger_(incoming['Jurusan Terpakai'],'Jurusan Terpakai');if(used>installed)insduContractError_('INSDU_JURUSAN_RELATION_INVALID','Jurusan Terpakai harus sama dengan atau lebih kecil dari Jurusan Terpasang.');return{installed:installed,used:used};}
var INSDU_CAPACITY_OPTIONS_=[25,50,100,160,200,250];
function validateInsduCapacity_(incoming){var value=Number(String(incoming.Kapasitas==null?'':incoming.Kapasitas).trim().replace(',','.'));if(INSDU_CAPACITY_OPTIONS_.indexOf(value)<0)insduContractError_('INSDU_CAPACITY_INVALID','Kapasitas wajib dipilih: 25, 50, 100, 160, 200, atau 250 kVA.');incoming.Kapasitas=value;return value;}
function insduMaximumPhaseCurrent_(capacity){return capacity*1000/(Math.sqrt(3)*400);}
var INSDU_CURRENT_FIELDS_=['Beban Utama R (A) WBP','Beban Utama S (A) WBP','Beban Utama T (A) WBP','Beban Jurusan N (A) WBP','Beban Utama R (A) LWBP','Beban Utama S (A) LWBP','Beban Utama T (A) LWBP','Beban Jurusan N (A) LWBP'];
var INSDU_VOLTAGE_FIELDS_=['Tegangan R-S (V) WBP','Tegangan S-T (V) WBP','Tegangan R-T (V) WBP','Tegangan R-N (V) WBP','Tegangan S-N (V) WBP','Tegangan T-N (V) WBP','Tegangan R-S (V) LWBP','Tegangan S-T (V) LWBP','Tegangan R-T (V) LWBP','Tegangan R-N (V) LWBP','Tegangan S-N (V) LWBP','Tegangan T-N (V) LWBP'];
function insduFiniteNumber_(value,label){var text=String(value==null?'':value).trim();if(!text)insduContractError_('INSDU_MEASUREMENT_REQUIRED',label+' wajib diisi.');if(!/^(?:0|[1-9]\d*)(?:[.,]\d+)?$/.test(text))insduContractError_('INSDU_MEASUREMENT_INVALID',label+' wajib berupa angka finite dan tidak negatif.');var number=Number(text.replace(',','.'));if(!isFinite(number))insduContractError_('INSDU_MEASUREMENT_INVALID',label+' wajib berupa angka finite.');return number;}
function validateInsduMeasurements_(incoming){var currents={},voltages={};INSDU_CURRENT_FIELDS_.forEach(function(field){currents[field]=insduFiniteNumber_(incoming[field],field);});INSDU_VOLTAGE_FIELDS_.forEach(function(field){var value=insduFiniteNumber_(incoming[field],field);if(value<100||value>999)insduContractError_('INSDU_VOLTAGE_RANGE_INVALID',field+' wajib berada pada rentang 100 sampai 999 V.');voltages[field]=value;});return{currents:currents,voltages:voltages};}
function insduCoordinate_(value,label){var parts=String(value==null?'':value).trim().split(','),latitude=Number(parts[0]),longitude=Number(parts[1]);if(parts.length!==2||!isFinite(latitude)||!isFinite(longitude)||latitude< -90||latitude>90||longitude< -180||longitude>180||(latitude===0&&longitude===0))insduContractError_('INSDU_COORDINATE_INVALID',label+' tidak valid.');return{latitude:latitude,longitude:longitude};}
function insduCaptureTime_(value,label){var text=String(value==null?'':value).trim(),match=/^(\d{2})\s+(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember)\s+(\d{4}),\s+(\d{2}):(\d{2}):(\d{2})$/.exec(text);if(!match)insduContractError_('INSDU_CAPTURE_TIME_INVALID',label+' wajib memakai format dd MMMM yyyy, HH:mm:ss.');var months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],day=Number(match[1]),month=months.indexOf(match[2]),year=Number(match[3]),hour=Number(match[4]),minute=Number(match[5]),second=Number(match[6]),parsed=new Date(Date.UTC(year,month,day,hour,minute,second));if(year<2000||year>2100||hour>23||minute>59||second>59||parsed.getUTCFullYear()!==year||parsed.getUTCMonth()!==month||parsed.getUTCDate()!==day||parsed.getUTCHours()!==hour||parsed.getUTCMinutes()!==minute||parsed.getUTCSeconds()!==second)insduContractError_('INSDU_CAPTURE_TIME_INVALID',label+' bukan tanggal dan waktu yang valid.');return text;}
function insduCapture_(incoming,suffix){var coordinateKey='Koordinat Penginputan '+suffix,timeKey='Waktu Penginputan '+suffix;return{coordinate:insduCoordinate_(incoming[coordinateKey],coordinateKey),capturedAt:insduCaptureTime_(incoming[timeKey],timeKey)};}
function validateInsduCoordinates_(incoming){return{wbp:insduCapture_(incoming,'WBP'),lwbp:insduCapture_(incoming,'LWBP')};}
function insduDistanceMeters_(from,to){var rad=Math.PI/180,dLat=(to.latitude-from.latitude)*rad,dLong=(to.longitude-from.longitude)*rad,lat1=from.latitude*rad,lat2=to.latitude*rad,a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLong/2)*Math.sin(dLong/2);return Math.round(6371000*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))*10)/10;}
function insduCentralCoordinate_(row){var combined=String(row['Koordinat Gardu']==null?'':row['Koordinat Gardu']).trim();if(combined){try{return insduCoordinate_(combined,'Koordinat Gardu');}catch(_){}}var latitude=Number(String(row.Lat==null?'':row.Lat).trim().replace(',','.')),longitude=Number(String(row.Long==null?'':row.Long).trim().replace(',','.'));return isFinite(latitude)&&isFinite(longitude)&&latitude>=-90&&latitude<=90&&longitude>=-180&&longitude<=180&&(latitude!==0||longitude!==0)?{latitude:latitude,longitude:longitude}:null;}
function insduApplyServerDistances_(session,sheet,rows){var values=sheet.getDataRange().getDisplayValues(),headers=(values[0]||[]).map(function(v){return String(v).trim();}),targets=woVerifiedPrepareTargets_(session,values,headers,rows);return targets.prepared.map(function(target){var incoming={};Object.keys(target.incoming).forEach(function(key){incoming[key]=target.incoming[key];});var server={};headers.forEach(function(header,column){server[header]=values[target.rowIndex][column];});var gardu=insduCentralCoordinate_(server),captures=validateInsduCoordinates_(incoming);incoming['Jarak Antar Gardu ke Petugas (WBP)']=gardu?insduDistanceMeters_(gardu,captures.wbp.coordinate):'';incoming['Jarak Antar Gardu ke Petugas (LWBP)']=gardu?insduDistanceMeters_(gardu,captures.lwbp.coordinate):'';return incoming;});}
function syncWoInsduContract_(token,rows){if(!Array.isArray(rows)||rows.length>100)return fail_('BATCH_INVALID','Maksimal 100 WO per sinkronisasi.');try{for(var i=0;i<rows.length;i++){validateInsduJurusan_(rows[i]||{});validateInsduCoordinates_(rows[i]||{});validateInsduCapacity_(rows[i]||{});validateInsduMeasurements_(rows[i]||{});}var auth=cekSesi_(token);if(!auth.success)return auth;var access=woCoreAccess_(auth.sesi,'insdu');if(!access.success)return access;var source=woCoreSheet_(CONFIG.WO_INSDU_SHEET||'WO_Ins_Du'),normalizedRows=insduApplyServerDistances_(auth.sesi,source.sheet,rows);['kapasitas','jurusan terpasang','jurusan terpakai','koordinat penginputan wbp','waktu penginputan wbp','jarak antar gardu ke petugas (wbp)','koordinat penginputan lwbp','waktu penginputan lwbp','jarak antar gardu ke petugas (lwbp)'].forEach(function(header){if(WO_CORE_MUTABLE.insdu.indexOf(header)<0)WO_CORE_MUTABLE.insdu.push(header);});return syncWoCoreCommitted_(token,'insdu',CONFIG.WO_INSDU_SHEET||'WO_Ins_Du',normalizedRows);}catch(error){return fail_(error.insduCode||error.woCode||'INSDU_CONTRACT_INVALID',error.message||'Kontrak Insdu tidak valid.');}}
