'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../ZZZZZZZZZZZZZZZZZZZZZ_Rel07BehaviorGuard.js'),'utf8');
function load(){const s={normalize_:v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' '),sha256_:v=>crypto.createHash('sha256').update(String(v)).digest('hex'),digestBytes_:b=>crypto.createHash('sha256').update(Buffer.from(b)).digest('hex'),Utilities:{base64Decode:v=>[...Buffer.from(v,'base64')]},fail_:(kode,message)=>({success:false,kode,message}),headerIndex_:h=>Object.fromEntries(h.map((v,i)=>[String(v).trim().toLowerCase(),i])),OPJ_FINDING_TRANSPORT_KEYS_:{fototemuanbase64:true}};vm.createContext(s);vm.runInContext(source,s);return s;}
test('Temuan operation identity uses Kode Temuan, not parent Kode WO',()=>{const api=load(),id=api.operationJournalIdentity_('syncTemuanInspeksi',{row:{'Kode WO':'WO-1','Kode Temuan':'WO-1.TO-001',fotoTemuanBase64:Buffer.from('a').toString('base64'),fotoLingkunganBase64:Buffer.from('b').toString('base64')}},{username:'User.A'});assert.equal(id.objectId,'WO-1.TO-001');assert.match(id.operationId,/^[a-f0-9]{64}$/);});
test('photo changes alter operation id even when payload digest is unchanged',()=>{const api=load(),base={'Kode WO':'WO-1',clientPayloadDigest:'a'.repeat(64)};const one=api.operationJournalIdentity_('syncWoRow',{rows:[{...base,fotoSesudahBase64:Buffer.from('one').toString('base64')}]},{username:'u'});const two=api.operationJournalIdentity_('syncWoRow',{rows:[{...base,fotoSesudahBase64:Buffer.from('two').toString('base64')}]},{username:'u'});assert.notEqual(one.operationId,two.operationId);assert.equal(one.payloadDigest,base.clientPayloadDigest);});
test('supplied photo digest must match actual photo bytes',()=>{const api=load(),bytes=Buffer.from('photo-bytes'),encoded=bytes.toString('base64'),actual=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(api.opjPhotoDigest_({fotoSesudahBase64:encoded,clientPhotoDigest:actual},'fotoSesudahBase64','clientPhotoDigest'),actual);assert.throws(()=>api.opjPhotoDigest_({fotoSesudahBase64:encoded,clientPhotoDigest:'0'.repeat(64)},'fotoSesudahBase64','clientPhotoDigest'),/tidak cocok dengan byte foto/);});
test('unknown Temuan field fails instead of disappearing from comparison',()=>{const api=load();assert.throws(()=>api.opjFindingProjection_({'Kolom Baru':'x'},{'kode temuan':0}),/tidak memiliki kolom tujuan/);});
test('Temuan header validation requires write and receipt columns',()=>{const api=load(),result=api.validateTemuanHeaders_(['Kode WO','Kode Temuan']);assert.equal(result.success,false);assert.match(result.message,/folder path/);});
test('stale lease sweep rereads by operation id while holding lock',()=>{const body=source.slice(source.indexOf('function operationJournalSweepStaleLeases_'));assert.match(body,/operationJournalFind_\(freshSource, operationId\)/);assert.ok(body.indexOf('lock.waitLock')<body.indexOf('operationJournalFind_'));assert.ok(body.indexOf('operationJournalFind_')<body.indexOf("'State': 'needs-reconciliation'"));});
