import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import '../models/wo_insjar.dart';
import '../services/high_accuracy_location_service.dart';
import '../services/wo_insjar_repository.dart';
import 'temuan_tab.dart';

class WoInsjarFormScreen extends StatefulWidget {
  final WoInsjar? existing;
  final Map<String, dynamic> sesi;
  const WoInsjarFormScreen({super.key, this.existing, required this.sesi});
  @override State<WoInsjarFormScreen> createState() => _State();
}

class _State extends State<WoInsjarFormScreen> {
  static const ocean=Color(0xFF0A3E74),navy=Color(0xFF071B30),gold=Color(0xFFFFAE00),paleGold=Color(0xFFFFF4C7),muted=Color(0xFF64748B),line=Color(0xFFE2E8F0),page=Color(0xFFF4F7FB);
  final repo=WoInsjarRepository();
  LocationFix? awal,akhir; DateTime? mulai,selesai; double kms=0; String status=WoInsjar.statusMulai; bool gettingAwal=false,gettingAkhir=false,saving=false; double? accuracyAwal,accuracyAkhir;
  WoInsjar? get wo=>widget.existing; bool get readOnly=>WoInsjar.normalisasiStatus(status)==WoInsjar.statusSelesai; bool get ready=>awal!=null&&akhir!=null&&selesai!=null;
  @override void initState(){super.initState();final v=wo;kms=v?.realisasiKms??0;status=WoInsjar.normalisasiStatus(v?.statusWo);mulai=WoInsjar.parseStamp(v?.waktuMulai??'');selesai=WoInsjar.parseStamp(v?.waktuSelesai??'');awal=parse(v?.koordinatAwal??'');akhir=parse(v?.koordinatAkhir??'');}
  LocationFix? parse(String value){final p=value.split(',');if(p.length<2)return null;final a=double.tryParse(p[0].trim()),b=double.tryParse(p[1].trim());if(a==null||b==null)return null;return LocationFix(latitude:a,longitude:b,accuracy:5,capturedAt:DateTime.now(),samples:30,locked:true);}
  String get duration{if(mulai==null||selesai==null)return wo?.durasiPekerjaan.isNotEmpty==true?wo!.durasiPekerjaan:'-';return WoInsjar.hitungDurasi(mulai!,selesai!);}
  Future<void> coordinate(bool start)async{if(readOnly||saving||(!start&&awal==null))return;setState((){if(start){gettingAwal=true;accuracyAwal=null;}else{gettingAkhir=true;accuracyAkhir=null;}});try{final fix=await HighAccuracyLocationService.acquire(onSample:(_,a){if(mounted)setState((){if(start)accuracyAwal=a;else accuracyAkhir=a;});});if(!mounted)return;setState((){if(start){awal=fix;mulai??=fix.capturedAt;status=WoInsjar.statusDalam;}else{akhir=fix;selesai=fix.capturedAt;}if(awal!=null&&akhir!=null)kms=Geolocator.distanceBetween(awal!.latitude,awal!.longitude,akhir!.latitude,akhir!.longitude)/1000;});}catch(e){message('$e',true);}finally{if(mounted)setState((){gettingAwal=false;gettingAkhir=false;});}}
  Future<void> save()async{if(readOnly||wo==null||saving)return;setState(()=>saving=true);try{await repo.simpan(wo!.copyWith(koordinatAwal:awal?.coordinate,koordinatAkhir:akhir?.coordinate,realisasiKms:kms,waktuMulai:mulai==null?null:WoInsjar.stampLengkap(mulai!),waktuSelesai:selesai==null?null:WoInsjar.stampLengkap(selesai!),durasiPekerjaan:duration=='-'?null:duration,statusWo:ready?WoInsjar.statusSelesai:status,isDirty:true));if(mounted){message(ready?'WO siap disinkronkan.':'Progress inspeksi tersimpan.',false);Navigator.pop(context,true);}}catch(e){message('Gagal menyimpan WO: $e',true);}finally{if(mounted)setState(()=>saving=false);}}
  void message(String text,bool error)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text),backgroundColor:error?Colors.red.shade700:Colors.green.shade700));
  @override Widget build(BuildContext context){final item=wo;if(item==null)return const Scaffold(body:Center(child:Text('WO tidak ditemukan.')));return Scaffold(backgroundColor:page,appBar:AppBar(backgroundColor:ocean,foregroundColor:Colors.white,title:const Text('Inspeksi Jaringan',style:TextStyle(fontWeight:FontWeight.w800))),body:Column(children:[hero(item),Expanded(child:ListView(padding:const EdgeInsets.fromLTRB(16,0,16,24),children:[card('01','Area inspeksi',area(item)),const SizedBox(height:20),card('02','Koordinat pekerjaan',coordinates(),padding:EdgeInsets.zero),const SizedBox(height:20),card('03','Temuan inspeksi',findings(item),padding:EdgeInsets.zero),const SizedBox(height:20),card('04','Ringkasan pekerjaan',summary())]))]),bottomNavigationBar:readOnly?null:SafeArea(minimum:const EdgeInsets.fromLTRB(16,10,16,14),child:SizedBox(height:52,child:ElevatedButton(onPressed:saving?null:save,style:ElevatedButton.styleFrom(backgroundColor:gold,foregroundColor:navy,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(saving?'Menyimpan...':ready?'Simpan & Selesaikan WO':'Simpan Progress',style:const TextStyle(fontWeight:FontWeight.w900))))));}
  Widget hero(WoInsjar item)=>Container(width:double.infinity,margin:const EdgeInsets.fromLTRB(16,16,16,20),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:ocean,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('WORK ORDER',style:TextStyle(color:Color(0xFFB8DCEF),fontSize:11,fontWeight:FontWeight.w900,letterSpacing:1.3)),const SizedBox(height:8),Text(item.kodeWo,style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text('${item.ulp} • ${item.kodeUlp} • ${item.tanggal}',style:const TextStyle(color:Color(0xFFD5E8F3),fontSize:12))]));
  Widget card(String number,String title,Widget body,{EdgeInsets padding=const EdgeInsets.all(18)})=>Container(clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:line),boxShadow:const[BoxShadow(color:Color(0x0E071B30),blurRadius:20,offset:Offset(0,7))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Padding(padding:const EdgeInsets.all(18),child:Row(children:[Container(width:38,height:38,alignment:Alignment.center,decoration:BoxDecoration(color:paleGold,shape:BoxShape.circle,border:Border.all(color:gold)),child:Text(number,style:const TextStyle(color:Color(0xFF7A5700),fontSize:11,fontWeight:FontWeight.w900))),const SizedBox(width:12),Text(title,style:const TextStyle(color:navy,fontSize:17,fontWeight:FontWeight.w900))])),const Divider(height:1),Padding(padding:padding,child:body)]));
  Widget area(WoInsjar item)=>Column(children:[field('Penyulang',item.penyulang),const SizedBox(height:14),Row(children:[Expanded(child:field('Section awal',item.sectionAwal)),const SizedBox(width:12),Expanded(child:field('Section akhir',item.sectionAkhir))]),const SizedBox(height:14),field('Section pekerjaan',item.section),const SizedBox(height:14),field('Tier',item.tier)]);
  Widget field(String label,String value)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:muted,fontSize:12,fontWeight:FontWeight.w800)),const SizedBox(height:6),Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:12,vertical:11),decoration:BoxDecoration(color:const Color(0xFFF8FAFC),borderRadius:BorderRadius.circular(10)),child:Text(value.isEmpty?'-':value,style:const TextStyle(color:navy,fontWeight:FontWeight.w700)))]);
  Widget coordinates()=>Column(children:[coordinateRow('Titik awal pekerjaan',awal,gettingAwal,true,accuracyAwal),const Divider(height:1),coordinateRow('Titik akhir pekerjaan',akhir,gettingAkhir,false,accuracyAkhir)]);
  Widget coordinateRow(String title,LocationFix? fix,bool loading,bool start,double? accuracy){final locked=!start&&awal==null;final detail=loading?(accuracy==null?'Menunggu sampel GPS...':'Akurasi terbaik ${accuracy.toStringAsFixed(1)} m'):(fix==null?(locked?'Ambil titik awal terlebih dahulu':'Belum direkam'):'Akurasi ${fix.accuracyLabel}');return AnimatedOpacity(duration:const Duration(milliseconds:180),opacity:locked ? .55 : 1,child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:navy,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(fix?.coordinate??'-',style:const TextStyle(color:ocean,fontSize:13,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(detail,style:const TextStyle(color:muted,fontSize:12,fontWeight:FontWeight.w700)),if(!readOnly)...[const SizedBox(height:12),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:loading||saving||locked?null:()=>coordinate(start),icon:loading?const SizedBox(width:17,height:17,child:CircularProgressIndicator(strokeWidth:2.2)):const Icon(Icons.location_on_outlined),label:Text(loading?'Mencari koordinat...':'Ambil Koordinat')))]])));}
  Widget findings(WoInsjar item)=>SizedBox(height:390,child:TemuanTab(key:ValueKey('temuan-${item.kodeWo}'),wo:item,sesi:widget.sesi,canAddTemuan:awal!=null));
  Widget summary()=>Column(children:[sum('Realisasi kmS','${kms.toStringAsFixed(3)} km'),const Divider(height:22),sum('Waktu mulai',mulai==null?'-':WoInsjar.stampLengkap(mulai!)),const Divider(height:22),sum('Waktu selesai',selesai==null?'-':WoInsjar.stampLengkap(selesai!)),const Divider(height:22),sum('Durasi pekerjaan',duration),const Divider(height:22),sum('Status WO',status)]);
  Widget sum(String label,String value)=>Row(children:[SizedBox(width:122,child:Text(label,style:const TextStyle(color:muted,fontSize:12))),const SizedBox(width:8),Expanded(child:Text(value,textAlign:TextAlign.right,style:const TextStyle(color:navy,fontSize:13,fontWeight:FontWeight.w900)))]);
}
