import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;
import '../models/temuan_inspeksi.dart';
import '../models/wo_insjar.dart';
import '../services/high_accuracy_location_service.dart';
import '../services/photo_watermark_service.dart';
import '../services/temuan_repository.dart';
import '../theme/kopitiam_theme.dart';
import 'landscape_camera_screen.dart';

class WoTemuanFormScreen extends StatefulWidget{final WoInsjar wo;final Map<String,dynamic> sesi;const WoTemuanFormScreen({super.key,required this.wo,required this.sesi});@override State<WoTemuanFormScreen> createState()=>_State();}
class _State extends State<WoTemuanFormScreen>{
  final repo=TemuanRepository(),segmen=TextEditingController(),jarak=TextEditingController(),tinggi=TextEditingController();List<Map<String,dynamic>> masterTemuan=[],masterPohon=[];String kode='',tier='',foto='',lingkungan='';String? temuan,pohon,error;LocationFix? gps;bool loading=true,getting=false,capturing=false,saving=false;double? accuracy;
  String clean(String v)=>v.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'),'');
  String find(Map<String,dynamic> row,List<String> keys){for(final key in keys){final v='${row[key]??''}'.trim();if(v.isNotEmpty)return v;}final names=keys.map(clean).toSet();for(final e in row.entries){final v='${e.value??''}'.trim();if(names.contains(clean(e.key))&&v.isNotEmpty)return v;}return '';}
  bool sameTier(String value){if(value.trim().isEmpty)return true;final a=clean(tier),b=clean(value);return a==b||b==a.replaceFirst('tier','')||'tier$b'==a;}
  List<String> get options=>(masterTemuan.where((r){final o=clean(find(r,const['Object Inspeksi','Objek Inspeksi','Object','Objek','Jenis Object','Jenis Objek','Kategori']));final ok=o.isEmpty||o.contains('jaringan')||o.contains('insjar')||o.contains('saluran')||o.contains('line')||o.contains('jtm')||o.contains('jtr');return ok&&sameTier(find(r,const['Tier','Tingkat','Level']));}).map((r)=>find(r,const['Temuan','Nama Temuan','Jenis Temuan','Uraian Temuan'])).where((v)=>v.isNotEmpty).toSet().toList()..sort());
  List<String> get trees=>masterPohon.map((r)=>find(r,const['Jenis Pohon','Pohon','Nama'])).where((v)=>v.isNotEmpty).toSet().toList();bool get isRow=>repo.isRowC4a(temuan??'');String get priority=>temuan==null?'':repo.prioritas(temuan!,double.tryParse(jarak.text.replaceAll(',','.')),double.tryParse(tinggi.text.replaceAll(',','.')),masterTemuan);
  @override void initState(){super.initState();tier=widget.wo.tier.trim();init();}@override void dispose(){segmen.dispose();jarak.dispose();tinggi.dispose();super.dispose();}
  Future<void> init()async{try{if(tier.isEmpty)throw StateError('Tier Work Order belum tersedia. Unduh ulang WO setelah Tier diisi.');final v=await Future.wait([repo.kodeBaru(widget.wo.kodeWo),repo.master('Master_Temuan'),repo.master('Jenis Pohon')]);kode=v[0] as String;masterTemuan=v[1] as List<Map<String,dynamic>>;masterPohon=v[2] as List<Map<String,dynamic>>;}catch(e){error=e.toString().replaceFirst('Bad state: ','');}finally{if(mounted)setState(()=>loading=false);}}
  Future<void> getGps()async{if(getting||capturing||saving)return;setState((){getting=true;accuracy=null;});try{final v=await HighAccuracyLocationService.acquire(onSample:(_,a){if(mounted)setState(()=>accuracy=a);});if(mounted)setState(()=>gps=v);}catch(e){msg('Gagal mengambil koordinat: $e');}finally{if(mounted)setState(()=>getting=false);}}
  Future<String> take(String label)async{final captured=await LandscapeCameraScreen.capture(context,title:label);if(captured==null||captured.isEmpty)return '';final source=File(captured);if(!await source.exists())throw StateError('Foto kamera tidak tersimpan.');final now=DateTime.now();String two(int v)=>v.toString().padLeft(2,'0');final copy=await source.copy(p.join(p.dirname(source.path),'$kode.$label.${two(now.hour)}${two(now.minute)}${two(now.second)}.jpg'));return PhotoWatermarkService.render(sourcePath:copy.path,item:TemuanInspeksi(kodeTemuan:kode,kodeWo:widget.wo.kodeWo,ulp:widget.wo.ulp,penyulang:widget.wo.penyulang,section:widget.wo.section,segmen:segmen.text.trim(),jenisObject:'Jaringan',tier:tier,temuan:temuan??'',koordinat:gps?.coordinate??'',hari:WoInsjar.hariIndonesia[now.weekday-1],tanggal:WoInsjar.formatTanggal(now),waktuInput:WoInsjar.stampLengkap(now)),photoLabel:label);}
  Future<void> capture(bool primary)async{if(capturing||saving||getting)return;if(gps==null)return msg('Ambil koordinat temuan terlebih dahulu.');setState(()=>capturing=true);try{final path=await take(primary?'Foto Temuan':'Foto Lingkungan');if(mounted&&path.isNotEmpty)setState((){if(primary)foto=path;else lingkungan=path;});}catch(e){msg('$e');}finally{if(mounted)setState(()=>capturing=false);}}
  Future<void> save()async{if(saving||capturing||getting||loading)return;if(error!=null)return msg(error!);if(segmen.text.trim().isEmpty)return msg('Isi Segmen terlebih dahulu.');if(temuan==null||!options.contains(temuan))return msg('Pilih Temuan dari master data.');if(isRow&&(jarak.text.isEmpty||tinggi.text.isEmpty||pohon==null||priority.isEmpty))return msg('Lengkapi kriteria ROW.');if(gps==null||foto.isEmpty||lingkungan.isEmpty)return msg('Lengkapi koordinat dan foto dokumentasi.');setState(()=>saving=true);try{final now=DateTime.now(),coord=gps!.coordinate.split(',');final item=TemuanInspeksi(kodeTemuan:kode,kodeWo:widget.wo.kodeWo,kodeUiw:widget.wo.kodeUiw,kodeUp3:widget.wo.kodeUp3,kodeUlp:widget.wo.kodeUlp,ulp:widget.wo.ulp,hari:WoInsjar.hariIndonesia[now.weekday-1],tanggal:WoInsjar.formatTanggal(now),penyulang:widget.wo.penyulang,sectionAwal:widget.wo.sectionAwal,sectionAkhir:widget.wo.sectionAkhir,section:widget.wo.section,segmen:segmen.text.trim(),koordinat:gps!.coordinate,lat:coord.first.trim(),long:coord.length>1?coord[1].trim():'',jenisObject:'Jaringan',tier:tier,temuan:temuan!,jarak:isRow?double.tryParse(jarak.text.replaceAll(',','.')):null,jenisPohon:isRow?(pohon??''):'',tinggiPohon:isRow?double.tryParse(tinggi.text.replaceAll(',','.')):null,prioritas:priority,fotoTemuan:foto,fotoLingkungan:lingkungan,waktuInput:WoInsjar.stampLengkap(now),userInput:'${widget.sesi['username']??''}',folderPath:TemuanRepository.folder(widget.wo,'Jaringan',kode,now));await repo.simpan(item);if(!mounted)return;await showDialog<void>(context:context,barrierDismissible:false,builder:(c)=>AlertDialog(icon:const Icon(Icons.check_circle_rounded,color:KopitiamColors.success,size:48),title:const Text('Temuan Tersimpan'),content:Text('${item.kodeTemuan}\n${item.temuan}\n${item.prioritas}'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Tutup'))]));if(mounted)Navigator.pop(context,true);}catch(e){msg('Gagal menyimpan: $e');}finally{if(mounted)setState(()=>saving=false);}}
  void msg(String value)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(value)));InputDecoration decoration(String label)=>InputDecoration(labelText:label,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)));
  @override Widget build(BuildContext context)=>PopScope(canPop:!saving&&!capturing,child:Scaffold(backgroundColor:KopitiamColors.canvas,appBar:AppBar(title:const Text('Tambah Temuan Baru')),body:Column(children:[Expanded(child:AbsorbPointer(absorbing:saving||capturing,child:ListView(padding:const EdgeInsets.all(18),children:[read('KODE WORK ORDER',widget.wo.kodeWo),const SizedBox(height:14),read('TIER PARENT WO',tier),if(loading)const Padding(padding:EdgeInsets.only(top:14),child:LinearProgressIndicator()),if(error!=null)Padding(padding:const EdgeInsets.only(top:14),child:Text(error!,style:const TextStyle(color:KopitiamColors.danger))),const SizedBox(height:14),TextField(controller:segmen,decoration:decoration('Segmen *')),const SizedBox(height:14),DropdownButtonFormField<String>(key:ValueKey('temuan-$tier-$temuan-${options.length}'),initialValue:options.contains(temuan)?temuan:null,isExpanded:true,decoration:decoration('Temuan *'),hint:Text(options.isEmpty?'Data Temuan tidak tersedia':'Pilih Temuan'),items:options.map((v)=>DropdownMenuItem(value:v,child:Text(v,overflow:TextOverflow.ellipsis))).toList(),onChanged:options.isEmpty?null:(v)=>setState((){temuan=v;pohon=null;jarak.clear();tinggi.clear();})),if(isRow)...[const SizedBox(height:14),Row(children:[Expanded(child:TextField(controller:jarak,keyboardType:const TextInputType.numberWithOptions(decimal:true),onChanged:(_)=>setState((){}),decoration:decoration('Jarak (m) *'))),const SizedBox(width:10),Expanded(child:TextField(controller:tinggi,keyboardType:const TextInputType.numberWithOptions(decimal:true),onChanged:(_)=>setState((){}),decoration:decoration('Tinggi (m) *')))]),const SizedBox(height:14),DropdownButtonFormField<String>(initialValue:trees.contains(pohon)?pohon:null,decoration:decoration('Jenis Pohon *'),items:trees.map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>pohon=v))],const SizedBox(height:14),OutlinedButton.icon(onPressed:getting?null:getGps,icon:const Icon(Icons.my_location_rounded),label:Text(getting?'Akurasi ${accuracy?.toStringAsFixed(1)??'-'} m':gps?.coordinate??'Ambil Koordinat Temuan')),const SizedBox(height:14),Row(children:[Expanded(child:photoBox('Foto Temuan',foto,()=>capture(true))),const SizedBox(width:10),Expanded(child:photoBox('Foto Lingkungan',lingkungan,()=>capture(false)))])]))),SafeArea(minimum:const EdgeInsets.all(18),child:SizedBox(width:double.infinity,height:50,child:ElevatedButton(onPressed:saving?null:save,child:Text(saving?'Menyimpan...':'Simpan Temuan'))))])));
  Widget read(String label,String value)=>InputDecorator(decoration:decoration(label),child:Text(value.isEmpty?'-':value,style:const TextStyle(fontWeight:FontWeight.w900)));
  Widget photoBox(String label,String path,VoidCallback tap){final exists=path.isNotEmpty&&File(path).existsSync();return InkWell(onTap:tap,child:Container(height:130,alignment:Alignment.center,decoration:BoxDecoration(border:Border.all(color:KopitiamColors.line),borderRadius:BorderRadius.circular(14)),child:exists?ClipRRect(borderRadius:BorderRadius.circular(13),child:Image.file(File(path),width:double.infinity,height:130,fit:BoxFit.cover)):Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.camera_alt_rounded),const SizedBox(height:6),Text(label,textAlign:TextAlign.center)])));}
}
