import 'dart:convert';
import 'package:crypto/crypto.dart';
class SyncReceiptGuard {
  static const excluded={'clientpayloaddigest','clientphotodigest','foto sesudah base64','fotosesudahbase64','foto sesudah','link foto sesudah','folder path','jarak antar gardu ke petugas (wbp)','jarak antar gardu ke petugas (lwbp)'};
  static String _key(Object? value)=>'$value'.trim().toLowerCase().replaceAll(RegExp(r'\s+'),' ');
  static String _value(Object? value){if(value==null)return'';if(value is num){if(!value.isFinite)return'__invalid_number__';return value==value.roundToDouble()?value.toInt().toString():value.toString();}if(value is bool)return value?'true':'false';if(value is List)return'[${value.map(_value).join(',')}]';if(value is Map){final keys=value.keys.map(_key).toList()..sort();return'{${keys.map((key){final original=value.keys.firstWhere((candidate)=>_key(candidate)==key);return'$key:${_value(value[original])}';}).join(',')}}';}final text='$value'.trim().replaceAll(RegExp(r'\s+'),' '),number=double.tryParse(text.replaceAll(',','.'));if(RegExp(r'^-?\d+(?:[.,]\d+)?$').hasMatch(text)&&number!=null&&number.isFinite)return number==number.roundToDouble()?number.toInt().toString():number.toString();return text.toLowerCase();}
  static String payloadDigest(Map<String,dynamic> row){final keys=row.keys.map(_key).where((key)=>!excluded.contains(key)).toList()..sort();final canonical=keys.map((key){final original=row.keys.firstWhere((candidate)=>_key(candidate)==key);return'$key=${_value(row[original])}';}).join('\n');return sha256.convert(utf8.encode(canonical)).toString();}
  static String photoDigest(String base64Value)=>sha256.convert(base64Decode(base64Value)).toString();
  static List<Map<String,dynamic>> prepare(List<Map<String,dynamic>> rows)=>rows.map((source){final row=Map<String,dynamic>.from(source),photo='${source['fotoSesudahBase64']??source['Foto Sesudah Base64']??''}';row['clientPayloadDigest']=payloadDigest(row);if(photo.isNotEmpty)row['clientPhotoDigest']=photoDigest(photo);return row;}).toList();
  static bool verify(Map<String,dynamic> response,List<Map<String,dynamic>> rows){if(response['success']!=true||response['receipts'] is! List)return false;final receipts=response['receipts'] as List;if(receipts.length!=rows.length)return false;for(final row in rows){final code='${row['Kode WO']??''}'.trim(),ulp='${row['ULP']??''}'.trim(),date='${row['Tanggal Pekerjaan']??row['Tanggal']??''}'.trim(),digest='${row['clientPayloadDigest']??''}';final matches=receipts.whereType<Map>().where((receipt)=>receipt['committed']==true&&'${receipt['kodeWo']??''}'.trim()==code&&'${receipt['ulp']??''}'.trim()==ulp&&'${receipt['tanggal']??''}'.trim()==date&&'${receipt['payloadDigest']??''}'==digest).toList();if(matches.length!=1)return false;final photo='${row['clientPhotoDigest']??''}';if(photo.isNotEmpty){final receiptPhoto=matches.single['photo'];if(receiptPhoto is! Map||'${receiptPhoto['fileId']??''}'.isEmpty||'${receiptPhoto['digest']??''}'!=photo)return false;}}return true;}
}
