import 'dart:convert';
import 'package:sqflite/sqflite.dart';
import '../models/wo_insjar.dart';
import 'api_service.dart';
import 'sqlite_service.dart';

class WoSyncResult { final int total,diproses; final String? pesan; const WoSyncResult({required this.total,required this.diproses,this.pesan}); }

class WoInsjarRepository {
  WoInsjarRepository({SqliteService? database}) : _db=database??SqliteService.instance;
  final SqliteService _db; static const table='wo_insjar';
  Future<Database> _database() => _db.database;
  Future<List<WoInsjar>> semua() async { final db=await _database(); final rows=await db.query(table,orderBy:"CASE status_wo WHEN '${WoInsjar.statusMulai}' THEN 0 WHEN '${WoInsjar.statusDalam}' THEN 1 ELSE 2 END, tanggal DESC, kode_wo DESC"); return rows.map(WoInsjar.fromMap).toList(); }
  Future<List<WoInsjar>> belumTersinkron() async { final db=await _database(); final rows=await db.query(table,where:'is_dirty = 1 AND status_wo = ?',whereArgs:[WoInsjar.statusSelesai]); return rows.map(WoInsjar.fromMap).toList(); }
  Future<WoInsjar?> cariKode(String code) async { final db=await _database(); final rows=await db.query(table,where:'kode_wo = ?',whereArgs:[code],limit:1); return rows.isEmpty?null:WoInsjar.fromMap(rows.first); }
  Future<void> simpan(WoInsjar wo,{bool tandaiDirty=true}) async { final db=await _database(); final done=WoInsjar.normalisasiStatus(wo.statusWo)==WoInsjar.statusSelesai; final values=wo.copyWith(isDirty:tandaiDirty&&done).toMap()..['synced_at']=DateTime.now().toUtc().toIso8601String(); await db.insert(table,values,conflictAlgorithm:ConflictAlgorithm.replace); }
  Future<void> mulaiPengerjaan(String code) async { final db=await _database(); await db.update(table,{'status_wo':WoInsjar.statusDalam,'is_dirty':0},where:'kode_wo = ? AND status_wo = ?',whereArgs:[code,WoInsjar.statusMulai]); }
  Future<String> buatKodeWo({required String kodeUlp,required DateTime tanggal}) async { String two(int v)=>v.toString().padLeft(2,'0'); final prefix='INSJAR-$kodeUlp${two(tanggal.year%100)}${two(tanggal.month)}${two(tanggal.day)}'; final db=await _database(); final rows=await db.rawQuery('SELECT kode_wo FROM $table WHERE kode_wo LIKE ? ORDER BY kode_wo DESC',['$prefix%']); var max=0; for(final row in rows){final code='${row['kode_wo']??''}';if(code.startsWith(prefix)){final n=int.tryParse(code.substring(prefix.length))??0;if(n>max)max=n;}} return '$prefix${(max+1).toString().padLeft(3,'0')}'; }
  Future<WoSyncResult> download(String token) async { final db=await _database(); final response=await ApiService.getWoInsjar(token); if(response['success']!=true||response['rows'] is! List)return WoSyncResult(total:0,diproses:0,pesan:'${response['message']??'Data WO tidak valid.'}'); var added=0,available=0; final stamp=DateTime.now().toUtc().toIso8601String(); await db.transaction((txn)async{for(final raw in response['rows'] as List){if(raw is! Map)continue;final remote=WoInsjar.fromRemote(Map<String,dynamic>.from(raw));if(remote.kodeWo.isEmpty||WoInsjar.normalisasiStatus(remote.statusWo)==WoInsjar.statusSelesai)continue;available++;final old=await txn.query(table,columns:['kode_wo'],where:'kode_wo = ?',whereArgs:[remote.kodeWo],limit:1);if(old.isNotEmpty)continue;final values=remote.toMap()..['synced_at']=stamp..['is_dirty']=0;await txn.insert(table,values);added++;}await txn.insert('sync_metadata',{'key':'WO_Ins_Jar','synced_at':stamp,'row_count':available,'status':'success','error_message':''},conflictAlgorithm:ConflictAlgorithm.replace);}); return WoSyncResult(total:available,diproses:added); }
  Future<WoSyncResult> sinkron(String token) async { final pending=await belumTersinkron();if(pending.isEmpty)return const WoSyncResult(total:0,diproses:0,pesan:'Belum ada WO selesai yang siap disinkronkan.');final response=await ApiService.syncWoInsjar(token,pending.map((w)=>w.toRemote()).toList());if(response['success']!=true)return WoSyncResult(total:pending.length,diproses:0,pesan:'${response['message']??'Sinkronisasi WO gagal.'}');final processed=(response['diproses'] as num?)?.toInt()??pending.length;if(processed!=pending.length)return WoSyncResult(total:pending.length,diproses:processed,pesan:'Konfirmasi server tidak lengkap. Data lokal dipertahankan agar aman.');final db=await _database();await db.transaction((txn)async{for(final wo in pending)await txn.delete(table,where:'kode_wo = ? AND status_wo = ?',whereArgs:[wo.kodeWo,WoInsjar.statusSelesai]);});return WoSyncResult(total:pending.length,diproses:processed); }
  Future<List<String>> daftarPenyulang() async { final db=await _database();final rows=await db.query('master_data_rows',columns:['payload_json'],where:'dataset = ?',whereArgs:['Master_Penyulang']);final result=<String>{};for(final row in rows){try{final p=jsonDecode('${row['payload_json']}');if(p is! Map)continue;for(final key in ['Nama Penyulang','Penyulang','nama_penyulang']){final v='${p[key]??''}'.trim();if(v.isNotEmpty){result.add(v);break;}}}catch(_){}}return result.toList()..sort(); }
}
