import 'package:flutter/material.dart';
import '../../models/har_execution.dart';
import '../../models/wo_insdu.dart';
import '../../models/wo_insjar.dart';
import '../../models/wo_row.dart';
import '../../services/network_status_service.dart';
import '../../services/wo_insdu_repository.dart';
import '../../services/wo_insjar_repository.dart';
import '../../services/wo_row_repository.dart';
import '../../theme/kopitiam_theme.dart';
import 'welcome_coffee_mark.dart';
import 'wo_summary_card.dart';

typedef NetworkProbe = Future<bool> Function();
class WelcomeCard extends StatefulWidget { final Map<String,dynamic> sesi; final NetworkProbe? networkProbe; const WelcomeCard({super.key,required this.sesi,this.networkProbe}); @override State<WelcomeCard> createState()=>_WelcomeCardState(); }
class _WelcomeCardState extends State<WelcomeCard> with WidgetsBindingObserver { bool? _online; bool _checking=false,_loadingSummary=false; int _total=0,_waiting=0,_progress=0,_done=0; NetworkProbe get _probe=>widget.networkProbe??NetworkStatusService.isOnline; String get _identity=>'${widget.sesi['subTim']??widget.sesi['tim']??''} ${widget.sesi['username']??''}'.toLowerCase(); bool get _showNonHarSummary=>HarExecution.allowedTypes(widget.sesi).isEmpty; bool get _isInsdu=>_identity.contains('inspeksi gardu')||_identity.contains('insdu'); bool get _isRow=>!_isInsdu&&_identity.contains('row');
@override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);_checkNetwork();_loadSummary();}@override void didUpdateWidget(covariant WelcomeCard oldWidget){super.didUpdateWidget(oldWidget);if(_showNonHarSummary)_loadSummary();}@override void didChangeAppLifecycleState(AppLifecycleState state){if(state==AppLifecycleState.resumed){_checkNetwork();_loadSummary();}} Future<void> _checkNetwork()async{if(_checking)return;_checking=true;try{final online=await _probe();if(mounted&&online!=_online)setState(()=>_online=online);}finally{_checking=false;}} Future<void> _loadSummary()async{if(!_showNonHarSummary||_loadingSummary)return;_loadingSummary=true;try{var total=0,waiting=0,progress=0,done=0;if(_isInsdu){final items=await WoInsduRepository().semua();total=items.length;waiting=items.where((i)=>WoInsdu.normalisasiStatus(i.statusWo)==WoInsdu.statusMulai).length;progress=items.where((i)=>WoInsdu.normalisasiStatus(i.statusWo)==WoInsdu.statusDalam).length;done=items.where((i)=>WoInsdu.normalisasiStatus(i.statusWo)==WoInsdu.statusSelesai).length;}else if(_isRow){final items=await WoRowRepository().semua();total=items.length;waiting=items.where((i)=>WoRow.normalisasiStatus(i.statusWo)==WoRow.statusPenugasan).length;progress=items.where((i)=>WoRow.normalisasiStatus(i.statusWo)==WoRow.statusProgress).length;done=items.where((i)=>WoRow.normalisasiStatus(i.statusWo)==WoRow.statusSelesai).length;}else{final items=await WoInsjarRepository().semua();total=items.length;waiting=items.where((i)=>WoInsjar.normalisasiStatus(i.statusWo)==WoInsjar.statusMulai).length;progress=items.where((i)=>WoInsjar.normalisasiStatus(i.statusWo)==WoInsjar.statusDalam).length;done=items.where((i)=>WoInsjar.normalisasiStatus(i.statusWo)==WoInsjar.statusSelesai).length;}if(!mounted)return;setState((){_total=total;_waiting=waiting;_progress=progress;_done=done;});}finally{_loadingSummary=false;}}
@override void dispose(){WidgetsBinding.instance.removeObserver(this);super.dispose();} String _dateText(){final now=DateTime.now();const days=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'],months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return '${days[now.weekday-1]}, ${now.day} ${months[now.month-1]} ${now.year}';}
@override Widget build(BuildContext context){final subTim=(widget.sesi['subTim']??widget.sesi['tim']??'-').toString(),ulp=(widget.sesi['ulp']??'-').toString(),bidang=(widget.sesi['bidang']??widget.sesi['Bidang']??'-').toString();return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_welcomeCard(subTim:subTim,ulp:ulp,bidang:bidang),if(_showNonHarSummary)...[const SizedBox(height:16),if(_loadingSummary&&_total==0)const LinearProgressIndicator()else if(_isRow)WoSummaryCard.row(total:_total,penugasan:_waiting,progress:_progress,selesai:_done)else WoSummaryCard.insjar(total:_total,menunggu:_waiting,sedang:_progress,selesai:_done)]]);}
Widget _welcomeCard({required String subTim,required String ulp,required String bidang})=>Container(key:const ValueKey('welcome-card'),width:double.infinity,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF176DA8),Color(0xFF004D8C),Color(0xFF004279)],stops:[0,.42,1],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFF2A79B2)),boxShadow:const[BoxShadow(color:Color(0x33071F33),blurRadius:30,offset:Offset(0,16))]),child:Stack(children:[Positioned.fill(child:IgnorePointer(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(colors:[Color(0x1CFBFDFE),Color(0x00FBFDFE)],begin:Alignment.topCenter,end:Alignment.center))))),Positioned(left:0,top:28,child:Container(width:6,height:72,decoration:const BoxDecoration(gradient:LinearGradient(colors:[KopitiamColors.yellow,KopitiamColors.gold],begin:Alignment.topCenter,end:Alignment.bottomCenter),borderRadius:BorderRadius.horizontal(right:Radius.circular(8))))),Padding(padding:const EdgeInsets.fromLTRB(22,20,18,20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_dateText(),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:KopitiamColors.yellow,fontSize:11,fontWeight:FontWeight.w900,letterSpacing:.35)),const SizedBox(height:8),const Text('Semangat Pagi,',style:TextStyle(color:KopitiamColors.surface,fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(subTim,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:KopitiamColors.surface,fontSize:25,fontWeight:FontWeight.w900,letterSpacing:-.35,shadows:[Shadow(color:Color(0x47071F33),offset:Offset(0,2),blurRadius:2)]))])),const SizedBox(width:8),Material(color:Colors.transparent,child:InkWell(onTap:_checking?null:_checkNetwork,borderRadius:BorderRadius.circular(100),child:_NetworkChip(online:_online)))]),const SizedBox(height:18),const Divider(color:Color(0xA6FBFDFE),height:1),const SizedBox(height:16),Stack(alignment:Alignment.bottomRight,children:[Padding(padding:const EdgeInsets.only(right:52),child:Row(children:[Expanded(child:_info('UNIT KERJA',ulp)),const SizedBox(width:18),Expanded(child:_info('BIDANG',bidang))])),const WelcomeCoffeeMark()])]))]);
Widget _info(String label,String value)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:KopitiamColors.yellow,fontSize:9,fontWeight:FontWeight.w900,letterSpacing:.45)),const SizedBox(height:4),Text(value.isEmpty?'-':value,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:KopitiamColors.surface,fontSize:13,fontWeight:FontWeight.w800))]);}
class _NetworkChip extends StatelessWidget{final bool? online;const _NetworkChip({required this.online});@override Widget build(BuildContext context){final color=online==true?KopitiamColors.success:online==false?KopitiamColors.danger:KopitiamColors.muted;final label=online==true?'ONLINE':online==false?'OFFLINE':'CEK...';return Semantics(label:'Status jaringan $label. Ketuk untuk periksa ulang.',liveRegion:true,child:Container(key:const ValueKey('network-status-chip'),padding:const EdgeInsets.symmetric(horizontal:9,vertical:7),decoration:BoxDecoration(color:KopitiamColors.navy,borderRadius:BorderRadius.circular(100),border:Border.all(color:KopitiamColors.surface),boxShadow:const[BoxShadow(color:Color(0x33071F33),blurRadius:7,offset:Offset(0,3))]),child:Row(mainAxisSize:MainAxisSize.min,children:[Container(key:const ValueKey('network-status-dot'),width:9,height:9,decoration:BoxDecoration(color:color,shape:BoxShape.circle)),const SizedBox(width:7),Text(label,style:const TextStyle(color:KopitiamColors.surface,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:.55))])));}}
